# Generated by Django 4.1.3 on 2022-12-16 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Issuer', models.CharField(max_length=200)),
                ('URL', models.URLField()),
                ('Date', models.DateField()),
                ('Description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=100)),
                ('Issuer', models.CharField(max_length=100)),
                ('URL', models.URLField()),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CreateResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('slug', models.CharField(max_length=225)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute', models.CharField(max_length=400)),
                ('Degree', models.CharField(max_length=200)),
                ('School', models.CharField(max_length=200)),
                ('URL', models.URLField()),
                ('City', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField(blank=True)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Level', models.CharField(choices=[('Beginner', 'Beginner'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='beginner', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('URL', models.URLField()),
                ('Summary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('URL', models.URLField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Relationship', models.CharField(max_length=100)),
                ('Phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Level', models.CharField(choices=[('Beginner', 'Beginner'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=50)),
                ('SubSkill', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=100)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('URL', models.URLField()),
                ('Summary', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Position', models.CharField(max_length=200)),
                ('Employer', models.CharField(max_length=100)),
                ('Url', models.URLField()),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField(blank=True)),
                ('Website', models.URLField(max_length=300)),
                ('Summary', models.CharField(max_length=400)),
                ('present', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to=None)),
                ('Full_Name', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('Phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('Gender', models.CharField(max_length=300)),
                ('Description', models.CharField(max_length=100)),
                ('Summary', models.CharField(max_length=400)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Postal', models.IntegerField()),
                ('saved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.createresume')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Website', models.URLField(max_length=360)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
