# Generated by Django 4.1.3 on 2022-12-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved',
        ),
    ]
