# Generated by Django 4.1.3 on 2022-12-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_projects_enddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='EndDate',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='StartDate',
        ),
    ]
